/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { LessonSegment } from '../types.ts';

export const SAMPLE_LESSONS: LessonSegment[] = [
  {
    id: 'lesson-normalization',
    topic: 'DBMS • Normalization',
    englishText: 'Normalization reduces unnecessary data redundancy in a database.',
    tamilMeaning: 'இந்த sentence-ல சொல்ல வருவது என்னனா, database-ல ஒரே தகவல் தேவையில்லாமல் பல முறை சேமிக்கப்படுவதை Normalization குறைக்கிறது.',
    tanglishMeaning: 'Database-la data thevai illama repeat aagi waste aaguradha Normalization kuraikudhu.',
    audioDurationSeconds: 6,
    importantWords: [
      {
        id: 'word-normalization',
        word: 'Normalization',
        tamilMeaning: 'தரவு முறைப்படுத்துதல் / இயல்பாக்கம்',
        tanglish: 'Normalization',
        partOfSpeech: 'database term',
        explanation: 'A systematic database design technique to organize tables and reduce redundant repetitive data.',
        tamilExplanation: 'Database அட்டவணைகளை சீரமைத்து தேவையற்ற தரவு நகல் சேமிப்பை நீக்கும் முறை.',
        example: 'Applying normalization up to Third Normal Form eliminates anomalies in our student table.',
        tamilExample: 'மாணவர் அட்டவணையில் இயல்பாக்கத்தைப் பயன்படுத்துவது தரவு முரண்பாடுகளைத் தவிர்க்கிறது.',
        topicNumber: 39,
        glossaryTopic: 'Normalization',
      },
      {
        id: 'word-redundancy',
        word: 'redundancy',
        tamilMeaning: 'தேவையற்ற நகல் / மீண்டும் மீண்டும் இருத்தல்',
        tanglish: 'redundancy',
        partOfSpeech: 'noun',
        explanation: 'Unnecessary duplication of the exact same data across multiple records or tables.',
        tamilExplanation: 'ஒரே தரவு பல இடங்களில் தேவையின்றி மீண்டும் மீண்டும் சேமிக்கப்படுவது.',
        example: 'Data redundancy wastes expensive disk storage and leads to update inconsistencies.',
        tamilExample: 'தேவையற்ற தரவு நகல் சேமிப்பு நினைவகத்தை வீணடிப்பதோடு முரண்பாடுகளையும் ஏற்படுத்தும்.',
      },
      {
        id: 'word-database',
        word: 'database',
        tamilMeaning: 'தரவுத்தளம்',
        tanglish: 'database',
        partOfSpeech: 'noun',
        explanation: 'An organized, systematic collection of structured data stored electronically in a computer system.',
        tamilExplanation: 'தகவல்களை முறையாக ஒழுங்கமைத்து சேமித்து வைக்கும் மின்னணு தரவுக் களஞ்சியம்.',
        example: 'A university database manages student admissions, course enrollments, and semester grades.',
        tamilExample: 'பல்கலைக்கழக தரவுத்தளம் மாணவர் சேர்க்கை மற்றும் மதிப்பெண்களை பாதுகாப்பாக நிர்வகிக்கிறது.',
        topicNumber: 2,
        glossaryTopic: 'Database',
      },
    ],
  },
  {
    id: 'lesson-foreign-key',
    topic: 'DBMS • Relational Model',
    englishText: 'A foreign key connects one table with another table.',
    tamilMeaning: 'இந்த sentence-ல ஆசிரியர் என்ன சொல்றாருன்னா, ஒரு table-ஐ இன்னொரு table-கூட link பண்ணி relationship உருவாக்க Foreign key பயன்படுது.',
    tanglishMeaning: 'Foreign key use panni rendu table-a link panni relation create panrom.',
    audioDurationSeconds: 6,
    importantWords: [
      {
        id: 'word-foreign-key',
        word: 'foreign key',
        tamilMeaning: 'வெளிப்புற விசை',
        tanglish: 'foreign key',
        partOfSpeech: 'database term',
        explanation: 'A foreign key is an attribute in a table that references the primary key in another table.',
        tamilExplanation: 'Foreign key என்பது ஒரு அட்டவணையில் இருந்து மற்றொரு அட்டவணையை தொடர்புபடுத்த பயன்படும் விசை.',
        example: 'In the Orders table, Customer_ID acts as a foreign key linking back to Customers.',
        tamilExample: 'Orders அட்டவணையில் உள்ள Customer_ID மற்றொரு அட்டவணையை இணைக்கும் foreign key ஆகும்.',
      },
      {
        id: 'word-table',
        word: 'table',
        tamilMeaning: 'அட்டவணை',
        tanglish: 'table',
        partOfSpeech: 'database term',
        explanation: 'A structured collection of related data organized into rows and columns in a database.',
        tamilExplanation: 'டேட்டாபேஸில் வரிசைகள் மற்றும் நெடுவரிசைகளாக ஒழுங்கமைக்கப்பட்ட தரவுகளின் தொகுப்பு.',
        example: 'A Students table stores records containing roll numbers, names, and grades.',
        tamilExample: 'Students அட்டவணை மாணவர்களின் தகவல்களை பாதுகாப்பாக சேமிக்கிறது.',
      },
      {
        id: 'word-connects',
        word: 'connects',
        tamilMeaning: 'இணைக்கிறது / தொடர்புபடுத்துகிறது',
        tanglish: 'link panradhu',
        partOfSpeech: 'verb',
        explanation: 'Links two separate entities or tables to establish a logical relationship.',
        tamilExplanation: 'இரு வெவ்வேறு அட்டவணைகளை அர்த்தமுள்ள உறவுமுறையோடு ஒன்றிணைப்பது.',
        example: 'The join query connects customer records with their purchase history.',
        tamilExample: 'இந்த query வாடிக்கையாளர் விவரங்களையும் அவர்களின் கொள்முதல் விவரங்களையும் இணைக்கிறது.',
      },
    ],
  },
  {
    id: 'lesson-keys',
    topic: 'DBMS • Relational Keys',
    englishText: 'Every primary key is a candidate key.',
    tamilMeaning: 'இந்த sentence-ல சொல்ல வருவது என்னனா, table-ல தனித்துவமா identify பண்ண தகுதியுள்ள candidate keys-ல இருந்துதான் ஒரு முக்கியமான primary key-ஐ தேர்ந்தெடுக்கிறோம், அதனால எல்லா primary key-உம் அடிப்படையில் ஒரு candidate key தான்.',
    tanglishMeaning: 'Table-la irukura candidate keys-la select pannapatta main unique key dhaan primary key.',
    audioDurationSeconds: 5,
    importantWords: [
      {
        id: 'word-primary-key',
        word: 'primary key',
        tamilMeaning: 'முதன்மை சாவி',
        tanglish: 'primary key',
        partOfSpeech: 'database term',
        explanation: 'A unique identifier for each record in a database table.',
        tamilExplanation: 'அட்டவணையில் ஒவ்வொரு பதிவையும் தனித்துவமாக அடையாளம் காணும் சாவி.',
        example: 'Student_ID is commonly designated as the primary key.',
        tamilExample: 'Student_ID பொதுவாக முதன்மை சாவியாக தேர்ந்தெடுக்கப்படுகிறது.',
      },
      {
        id: 'word-candidate-key',
        word: 'candidate key',
        tamilMeaning: 'வேட்பாளர் சாவி',
        tanglish: 'candidate key',
        partOfSpeech: 'database term',
        explanation: 'A minimal superkey capable of uniquely identifying any database record.',
        tamilExplanation: 'முதன்மை சாவியாக தேர்ந்தெடுக்கப்பட தகுதியுள்ள அனைத்து தனித்துவ சாவிகள்.',
        example: 'Both Email and Phone can be candidate keys in a user profile.',
        tamilExample: 'Email மற்றும் Phone இரண்டும் candidate keys ஆக இருக்கலாம்.',
      },
    ],
  },
  {
    id: 'lesson-photosynthesis',
    topic: 'Biology • Plant Sciences',
    englishText:
      'Photosynthesis is the process by which green plants convert light energy into chemical energy.',
    tamilMeaning:
      'ஒளிச்சேர்க்கை என்பது பச்சைத் தாவரங்கள் சூரிய ஒளி ஆற்றலை வேதியியல் ஆற்றலாக மாற்றி உணவை உருவாக்கும் செயல்முறையாகும்.',
    tanglishMeaning:
      'Plants sunlight-a use panni food prepare panra natural process dhaan photosynthesis.',
    audioDurationSeconds: 6,
    importantWords: [
      {
        id: 'word-photosynthesis',
        word: 'Photosynthesis',
        tamilMeaning: 'ஒளிச்சேர்க்கை',
        tanglish: 'Oli serkkai',
        partOfSpeech: 'noun',
        explanation: 'The natural process plants use to produce food using sunlight, water, and air.',
        tamilExplanation: 'சூரிய ஒளி, நீர் மற்றும் காற்றைப் பயன்படுத்தி தாவரங்கள் உணவு தயாரிக்கும் முறை.',
        example: 'During the day, trees carry out photosynthesis and release fresh oxygen into the air.',
        tamilExample: 'பகல் நேரத்தில் மரங்கள் ஒளிச்சேர்க்கை செய்து தூய ஆக்சிஜனை காற்றில் வெளியிடுகின்றன.',
      },
      {
        id: 'word-process',
        word: 'process',
        tamilMeaning: 'செயல்முறை / படிமுறை',
        tanglish: 'Seyalmurai',
        partOfSpeech: 'noun',
        explanation: 'A series of steps or actions taken to achieve a specific result.',
        tamilExplanation: 'ஒரு குறிப்பிட்ட முடிவை அடைய படிப்படியாக செய்யப்படும் செயல்கள்.',
        example: 'Boiling water to make tea is a simple step-by-step process.',
        tamilExample: 'தேநீர் தயாரிப்பது ஒரு எளிய படிப்படியான செயல்முறை ஆகும்.',
      },
      {
        id: 'word-convert',
        word: 'convert',
        tamilMeaning: 'மாற்று / உருமாறுதல்',
        tanglish: 'Maathru / Maaruthal',
        partOfSpeech: 'verb',
        explanation: 'To change something completely from one state or form into another.',
        tamilExplanation: 'ஒரு பொருளை அல்லது ஆற்றலை வேறு ஒரு வடிவமாக மாற்றுவது.',
        example: 'Water can convert into solid ice when temperature drops below zero.',
        tamilExample: 'மிகவும் குளிராகும்போது தண்ணீர் பனிக்கட்டியாக மாறுகிறது.',
      },
      {
        id: 'word-chemical-energy',
        word: 'chemical energy',
        tamilMeaning: 'வேதியியல் ஆற்றல்',
        tanglish: 'Vedhiyal aatral',
        partOfSpeech: 'noun phrase',
        explanation: 'Energy stored in bonds of chemical compounds like food, fuels, and batteries.',
        tamilExplanation: 'உணவு, எரிபொருள் அல்லது பேட்டரிகளில் சேமித்து வைக்கப்பட்டுள்ள உள் ஆற்றல்.',
        example: 'Our body uses the chemical energy in our food to walk and study.',
        tamilExample: 'நாம் சாப்பிடும் உணவில் உள்ள வேதியியல் ஆற்றலை உடலானது வேலை செய்யப் பயன்படுத்துகிறது.',
      },
      {
        id: 'word-light-energy',
        word: 'light energy',
        tamilMeaning: 'ஒளி ஆற்றல்',
        tanglish: 'Oli aatral',
        partOfSpeech: 'noun phrase',
        explanation: 'The radiant energy produced by light sources such as the sun or lamps.',
        tamilExplanation: 'சூரியன் அல்லது மின்விளக்குகளில் இருந்து வெளிப்படும் பிரகாசமான ஆற்றல்.',
        example: 'Solar panels absorb light energy and produce electricity for homes.',
        tamilExample: 'சோலார் பேனல்கள் சூரியனின் ஒளி ஆற்றலை உறிஞ்சி வீடுகளுக்கான மின்சாரமாக மாற்றுகின்றன.',
      },
    ],
  },
  {
    id: 'lesson-gravity',
    topic: 'Physics • Classical Mechanics',
    englishText:
      'Gravity is an invisible pulling force that accelerates objects toward the center of the Earth.',
    tamilMeaning:
      'ஈர்ப்பு விசை என்பது பொருட்களை பூமியின் மையத்தை நோக்கி இழுத்து விரைவுபடுத்தும் ஒரு கண்ணுக்குத் தெரியாத விசையாகும்.',
    tanglishMeaning:
      'Bhoomi ella objects-aiyum adhan center-ukku keezhe pull panra invisible power dhaan gravity.',
    audioDurationSeconds: 7,
    importantWords: [
      {
        id: 'word-gravity',
        word: 'Gravity',
        tamilMeaning: 'ஈர்ப்பு விசை',
        tanglish: 'Eerppu visai',
        partOfSpeech: 'noun',
        explanation: 'The universal force that attracts any object with mass toward Earth.',
        tamilExplanation: 'பொருட்களை பூமியை நோக்கி இழுக்கும் இயற்கை விசை.',
        example: 'When you drop an apple from your hand, gravity pulls it straight down.',
        tamilExample: 'கையிலிருந்து ஆப்பிள் நழுவினால், ஈர்ப்பு விசை அதை நேரடியாக தரைக்கு இழுக்கிறது.',
      },
      {
        id: 'word-invisible',
        word: 'invisible',
        tamilMeaning: 'கண்ணுக்குத் தெரியாத',
        tanglish: 'Kannukku theriyaadha',
        partOfSpeech: 'adjective',
        explanation: 'Impossible to see with our naked eyes.',
        tamilExplanation: 'நமது கண்களால் நேரில் பார்க்க முடியாத ஒன்று.',
        example: 'Air and wind are invisible, yet we can easily feel their cooling breeze.',
        tamilExample: 'காற்று கண்ணுக்குத் தெரிவதில்லை, ஆனால் அதன் குளிர்ந்த தென்றலை உணர முடியும்.',
      },
      {
        id: 'word-accelerates',
        word: 'accelerates',
        tamilMeaning: 'வேகப்படுத்துகிறது',
        tanglish: 'Vegapaduthugiradhu',
        partOfSpeech: 'verb',
        explanation: 'Causes something to move faster and gain speed over time.',
        tamilExplanation: 'ஒரு பொருளின் வேகத்தை விரைவாக அதிகரிக்கச் செய்வது.',
        example: 'Pressing the gas pedal in a car accelerates the vehicle forward.',
        tamilExample: 'காரில் ஆக்ஸிலேட்டரை அழுத்தும்போது வண்டி முன்னோக்கி வேகம் பிடிக்கிறது.',
      },
    ],
  },
  {
    id: 'lesson-circulatory',
    topic: 'Human Anatomy • Biology',
    englishText:
      'The human heart pumps oxygen-rich blood continuously through blood vessels to nourish vital organs.',
    tamilMeaning:
      'மனித இதயம் நமது முக்கிய உடல் உறுப்புகளுக்கு ஊட்டமளிக்க இரத்த நாளங்கள் வழியாக ஆக்சிஜன் நிறைந்த இரத்தத்தை இடைவிடாமல் பம்ப் செய்கிறது.',
    tanglishMeaning:
      'Heart unstop-a thudichu pure blood-a body organs ellathukkum supply pannudhu.',
    audioDurationSeconds: 8,
    importantWords: [
      {
        id: 'word-pumps',
        word: 'pumps',
        tamilMeaning: 'பீய்ச்சியடிக்கிறது / அழுத்தி அனுப்புகிறது',
        tanglish: 'Pump seigiradhu',
        partOfSpeech: 'verb',
        explanation: 'Forces liquid or gas to move continuously through pipes or vessels.',
        tamilExplanation: 'திரவத்தை ஒரு குறிப்பிட்ட திசையில் அழுத்தத்துடன் பீய்ச்சி அனுப்புவது.',
        example: 'A water motor pumps water from the ground well up to the rooftop tank.',
        tamilExample: 'மோட்டார் கிணற்றில் இருந்து தண்ணீரை வீட்டின் மேல் தொட்டிக்கு பம்ப் செய்கிறது.',
      },
      {
        id: 'word-nourish',
        word: 'nourish',
        tamilMeaning: 'ஊட்டமளித்தல் / வளர்த்தல்',
        tanglish: 'Oottam alithal',
        partOfSpeech: 'verb',
        explanation: 'To supply with substances necessary for life, growth, and health.',
        tamilExplanation: 'உயிரோடு இருக்கவும் ஆரோக்கியமாக வளரவும் தேவையான சத்துக்களை வழங்குவது.',
        example: 'Fresh fruits and healthy greens nourish our body with essential vitamins.',
        tamilExample: 'பழங்களும் கீரைகளும் நமது உடலுக்கு தேவையான சத்துக்களை வழங்கி ஊட்டமளிக்கின்றன.',
      },
      {
        id: 'word-vital-organs',
        word: 'vital organs',
        tamilMeaning: 'முக்கிய உடல் உறுப்புகள்',
        tanglish: 'Mukkiya udal uruppugal',
        partOfSpeech: 'noun phrase',
        explanation: 'Crucial body parts like the brain, heart, and lungs needed to stay alive.',
        tamilExplanation: 'மூளை, இதயம், நுரையீரல் போன்ற மனிதன் உயிர்வாழ மிக அவசியமான உறுப்புகள்.',
        example: 'Wearing a helmet while riding protects your brain, one of our vital organs.',
        tamilExample: 'தலைக்கவசம் அணிவது நமது முக்கிய உறுப்பான மூளையை பாதுகாக்கிறது.',
      },
    ],
  },
];
